version: "3.3"
services:
  mongodb_1:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive --replSet rs1 --port 27017 --keyFile /etc/mongo-replicas.key
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
    volumes:
      - mongodb_1_data:/data/db
      - ./mongo-replicas.key:/etc/mongo-replicas.key
  mongodb_2:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive --replSet rs1 --port 27017 --keyFile /etc/mongo-replicas.key
    ports:
      - 27117:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
    volumes:
      - mongodb_2_data:/data/db
      - ./mongo-replicas.key:/etc/mongo-replicas.key
  mongodb_3:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive --replSet rs1 --port 27017 --keyFile /etc/mongo-replicas.key
    ports:
      - 27217:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
    volumes:
      - mongodb_3_data:/data/db
      - ./mongo-replicas.key:/etc/mongo-replicas.key
volumes:
  mongodb_1_data:
  mongodb_2_data:
  mongodb_3_data:
